learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('user_accounts.urls')),
    path('', include('learning_logs.urls')),

]

learning_logs/urls.py
"""Defines URL patterns for learning logs app"""

from django.urls import path
from . import views


app_name = 'learning_logs'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),

    # topics
    path('topics/', views.topics, name='topics'),

    # Detail page for a single topic.
    path('topics/<int:topic_id>/', views.topic, name='topic'),

    # new topic
    path('create_topic/', views.create_topic, name='create_topic'),

    # new entry
    path('create_entry/<int:topic_id>/', views.create_entry, name='create_entry'),

    # edit entry
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
]

user_accounts/urls.py
"""URLs patterns for user accounts"""
from django.urls import path, include
from . import views

app_name = 'user_accounts'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Topic(models.Model):
    """A topic the user is learning about."""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Return a string representation of the model."""
        return self.text


class Entry(models.Model):
    """Something specific learned about a topic."""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Return a string representation of the model."""
        return self.text if len(self.text) < 50 else f"{self.text[:50]}..."

user_accounts/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms
from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': 'Entry:'}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Topic, Entry
from .forms import TopicForm, EntryForm
from django.contrib.auth.decorators import login_required
from django.http import Http404


# Create your views here.
def index(request):
    """The home page for Learning Log."""
    return render(request, 'learning_logs/index.html')


@login_required
def topics(request):
    """Show all topics"""
    all_topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics':all_topics}
    return render(request, 'learning_logs/topics.html', context)


@login_required
def topic(request, topic_id):
    """Show a topic"""
    a_topic = get_object_or_404(Topic, id=topic_id)
    if not is_user_authorised_access_topic(request, a_topic):
        raise Http404
    entries = a_topic.entry_set.order_by('date_added')
    context = {'topic': a_topic, 'entries': entries}

    return render(request, 'learning_logs/topic.html', context)


@login_required
def create_topic(request):
    if request.method == 'GET':
        # topic form request
        form = TopicForm()
    elif request.method == 'POST':
        # form submitted
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('learning_logs:topics')
    context = {'form': form}
    return render(request, 'learning_logs/create_topic.html', context)


@login_required
def create_entry(request, topic_id):
    """Add new Entry to a particular Topic"""
    entry_topic = get_object_or_404(Topic, id=topic_id)

    if not is_user_authorised_access_topic(request, entry_topic):
        raise Http404

    if request.method == 'GET':
        # entry form request
        form = EntryForm()
    elif request.method == 'POST':
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = entry_topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id=entry_topic.id)
    context = {'topic': entry_topic, 'form': form}
    return render(request, 'learning_logs/create_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    entry_to_edit = get_object_or_404(Entry, id=entry_id)
    entry_topic = entry_to_edit.topic
    if not is_user_authorised_access_topic(request, entry_topic):
        raise Http404

    if request.method == 'GET':
        # Edit form request
        form = EntryForm(instance=entry_to_edit)
    elif request.method == 'POST':
        # Edited form submitted
        form = EntryForm(instance=entry_to_edit, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id=entry_topic.id)
    context = {'entry': entry_to_edit, 'topic': entry_topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)


def is_user_authorised_access_topic(request, the_topic):
    """Check if currently authenticated user owns the Topic resource"""
    return the_topic.owner == request.user

user_accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


# Create your views here.
def register(request):
    """User account registration"""

    if request.method == 'GET':
        # Reqest for registration form
        form = UserCreationForm
    elif request.method == 'POST':
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()

            # log the user in and redirect
            login(request, new_user)
            return redirect('learning_logs:index')
    # return the registration form
    context = {'form': form}
    return render(request, 'registration/register.html', context)

learning_logs/templates/learning_logs/base.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Learning Log</title>
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
</head>
<body>
{% include 'learning_logs/partials/_navbar.html' %}
<main role="main" class="container">
    <div class="pb-2 mb-2 border-bottom">
        {% block page_header %}{% endblock page_header %}
    </div>
    <div>
        {% block content %}{% endblock content %}
    </div>
</main>

</body>
</html>

learning_logs/templates/learning_logs/create_entry.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
    <h3>Add Entry to <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h3>
{% endblock page_header %}

{% block content %}
    <form action="{% url 'learning_logs:create_entry' topic.id %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" name="submit">Add Entry</button>
    </form>
{% endblock content %}

learning_logs/templates/learning_logs/create_topic.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
    <h1>Add a new topic</h1>
{% endblock page_header %}

{% block content %}
    <form action="{% url 'learning_logs:create_topic' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" name="submit">Add topic</button>
    </form>
{% endblock content %}

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% block page_header %}
    <h3>Edit Entry for <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h3>
{% endblock page_header %}

{% block content %}
    <form action="{% url 'learning_logs:edit_entry' entry.id %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" name="submit">Save Changes</button>
    </form>
{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}
 {% block page_header %}
<div class="jumbotron">
    <h1 class="display-3">Track your learning.</h1>

    <p class="lead">Make your own Learning Log, and keep a list of the
        topics you're learning about. Whenever you learn something new
        about a topic, make an entry summarizing what you've learned.</p>
    {% if user.is_authenticated %}
         <a class="btn btn-lg btn-primary" href="{% url 'learning_logs:topics' %}"
       role="button">Go to Topics &raquo;</a>
    {% else %}
         <a class="btn btn-lg btn-primary" href="{% url 'user_accounts:register' %}"
       role="button">Register &raquo;</a>
    {% endif %}

</div>
 {% endblock page_header %}

{% block content %}
    <p>Learning Log helps you keep track of your learning, for any topic you're
     learning about.</p>
{% endblock content %}

learning_logs/templates/learning_logs/partials/_navbar.html
<nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">

    <a class="navbar-brand" href="{% url 'learning_logs:index' %}">
        Learning Log</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarCollapse" aria-controls="navbarCollapse"
            aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'learning_logs:topics' %}">
                    Topics</a></li>
        </ul>
        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <span class="navbar-text">Hello, {{ user.username }}.</span>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'user_accounts:logout' %}">Log out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'user_accounts:register' %}">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'user_accounts:login' %}">Log in</a></li>
            {% endif %}
        </ul>
    </div>

</nav>

learning_logs/templates/learning_logs/topic.html
{% extends "learning_logs/base.html" %}
{% block page_header %}
    <h1>Entries for topic: <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h1>
{% endblock page_header %}

{% block content %}
    {% for entry in entries %}
        <div class="card mb-3">
            <h4 class="card-header">
                {{ entry.date_added | date:'d M, Y H:i' }}
                <small>
                    <a href="{% url 'learning_logs:edit_entry' entry.id %}"> edit</a>
                </small>
            </h4>
            <div class="card-body">
                {{ entry.text | linebreaks }}
            </div>
        </div>
    {% empty %}
        <p class="h3">No entries for this topic</p>
    {% endfor %}
    <p><a href="{% url 'learning_logs:create_entry' topic.id %}">Add New Entry</a></p>
{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
     <h1>Topics</h1>
{% endblock page_header %}

{% block content %}
    <ul>
        {% for topic in topics %}
            <li class="h3"><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></li>
        {% empty %}
            <p class="h3">No topics have been added</p>
        {% endfor %}
    </ul>
    <p><a href="{% url 'learning_logs:create_topic' %}">Add New Topic</a></p>
{% endblock content %}